// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/breakpoint.proto

#ifndef PROTOBUF_proto_2fbreakpoint_2eproto__INCLUDED
#define PROTOBUF_proto_2fbreakpoint_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
namespace google {
namespace cloud {
namespace diagnostics {
namespace debug {
class Breakpoint;
class BreakpointDefaultTypeInternal;
extern BreakpointDefaultTypeInternal _Breakpoint_default_instance_;
class SourceLocation;
class SourceLocationDefaultTypeInternal;
extern SourceLocationDefaultTypeInternal _SourceLocation_default_instance_;
class Status;
class StatusDefaultTypeInternal;
extern StatusDefaultTypeInternal _Status_default_instance_;
class Variable;
class VariableDefaultTypeInternal;
extern VariableDefaultTypeInternal _Variable_default_instance_;
}  // namespace debug
}  // namespace diagnostics
}  // namespace cloud
namespace protobuf {
class Timestamp;
class TimestampDefaultTypeInternal;
extern TimestampDefaultTypeInternal _Timestamp_default_instance_;
}  // namespace protobuf
}  // namespace google

namespace google {
namespace cloud {
namespace diagnostics {
namespace debug {

namespace protobuf_proto_2fbreakpoint_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_proto_2fbreakpoint_2eproto

// ===================================================================

class Breakpoint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.cloud.diagnostics.debug.Breakpoint) */ {
 public:
  Breakpoint();
  virtual ~Breakpoint();

  Breakpoint(const Breakpoint& from);

  inline Breakpoint& operator=(const Breakpoint& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Breakpoint& default_instance();

  static inline const Breakpoint* internal_default_instance() {
    return reinterpret_cast<const Breakpoint*>(
               &_Breakpoint_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Breakpoint* other);

  // implements Message ----------------------------------------------

  inline Breakpoint* New() const PROTOBUF_FINAL { return New(NULL); }

  Breakpoint* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Breakpoint& from);
  void MergeFrom(const Breakpoint& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Breakpoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .google.cloud.diagnostics.debug.Variable variables = 4;
  int variables_size() const;
  void clear_variables();
  static const int kVariablesFieldNumber = 4;
  const ::google::cloud::diagnostics::debug::Variable& variables(int index) const;
  ::google::cloud::diagnostics::debug::Variable* mutable_variables(int index);
  ::google::cloud::diagnostics::debug::Variable* add_variables();
  ::google::protobuf::RepeatedPtrField< ::google::cloud::diagnostics::debug::Variable >*
      mutable_variables();
  const ::google::protobuf::RepeatedPtrField< ::google::cloud::diagnostics::debug::Variable >&
      variables() const;

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string method_name = 3;
  void clear_method_name();
  static const int kMethodNameFieldNumber = 3;
  const ::std::string& method_name() const;
  void set_method_name(const ::std::string& value);
  #if LANG_CXX11
  void set_method_name(::std::string&& value);
  #endif
  void set_method_name(const char* value);
  void set_method_name(const char* value, size_t size);
  ::std::string* mutable_method_name();
  ::std::string* release_method_name();
  void set_allocated_method_name(::std::string* method_name);

  // .google.cloud.diagnostics.debug.SourceLocation location = 2;
  bool has_location() const;
  void clear_location();
  static const int kLocationFieldNumber = 2;
  const ::google::cloud::diagnostics::debug::SourceLocation& location() const;
  ::google::cloud::diagnostics::debug::SourceLocation* mutable_location();
  ::google::cloud::diagnostics::debug::SourceLocation* release_location();
  void set_allocated_location(::google::cloud::diagnostics::debug::SourceLocation* location);

  // .google.protobuf.Timestamp create_time = 5;
  bool has_create_time() const;
  void clear_create_time();
  static const int kCreateTimeFieldNumber = 5;
  const ::google::protobuf::Timestamp& create_time() const;
  ::google::protobuf::Timestamp* mutable_create_time();
  ::google::protobuf::Timestamp* release_create_time();
  void set_allocated_create_time(::google::protobuf::Timestamp* create_time);

  // .google.protobuf.Timestamp final_time = 6;
  bool has_final_time() const;
  void clear_final_time();
  static const int kFinalTimeFieldNumber = 6;
  const ::google::protobuf::Timestamp& final_time() const;
  ::google::protobuf::Timestamp* mutable_final_time();
  ::google::protobuf::Timestamp* release_final_time();
  void set_allocated_final_time(::google::protobuf::Timestamp* final_time);

  // @@protoc_insertion_point(class_scope:google.cloud.diagnostics.debug.Breakpoint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::google::cloud::diagnostics::debug::Variable > variables_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr method_name_;
  ::google::cloud::diagnostics::debug::SourceLocation* location_;
  ::google::protobuf::Timestamp* create_time_;
  ::google::protobuf::Timestamp* final_time_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2fbreakpoint_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SourceLocation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.cloud.diagnostics.debug.SourceLocation) */ {
 public:
  SourceLocation();
  virtual ~SourceLocation();

  SourceLocation(const SourceLocation& from);

  inline SourceLocation& operator=(const SourceLocation& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SourceLocation& default_instance();

  static inline const SourceLocation* internal_default_instance() {
    return reinterpret_cast<const SourceLocation*>(
               &_SourceLocation_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SourceLocation* other);

  // implements Message ----------------------------------------------

  inline SourceLocation* New() const PROTOBUF_FINAL { return New(NULL); }

  SourceLocation* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SourceLocation& from);
  void MergeFrom(const SourceLocation& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SourceLocation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string path = 1;
  void clear_path();
  static const int kPathFieldNumber = 1;
  const ::std::string& path() const;
  void set_path(const ::std::string& value);
  #if LANG_CXX11
  void set_path(::std::string&& value);
  #endif
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  ::std::string* mutable_path();
  ::std::string* release_path();
  void set_allocated_path(::std::string* path);

  // int32 line = 2;
  void clear_line();
  static const int kLineFieldNumber = 2;
  ::google::protobuf::int32 line() const;
  void set_line(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:google.cloud.diagnostics.debug.SourceLocation)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr path_;
  ::google::protobuf::int32 line_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2fbreakpoint_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Variable : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.cloud.diagnostics.debug.Variable) */ {
 public:
  Variable();
  virtual ~Variable();

  Variable(const Variable& from);

  inline Variable& operator=(const Variable& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Variable& default_instance();

  static inline const Variable* internal_default_instance() {
    return reinterpret_cast<const Variable*>(
               &_Variable_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Variable* other);

  // implements Message ----------------------------------------------

  inline Variable* New() const PROTOBUF_FINAL { return New(NULL); }

  Variable* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Variable& from);
  void MergeFrom(const Variable& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Variable* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .google.cloud.diagnostics.debug.Variable members = 4;
  int members_size() const;
  void clear_members();
  static const int kMembersFieldNumber = 4;
  const ::google::cloud::diagnostics::debug::Variable& members(int index) const;
  ::google::cloud::diagnostics::debug::Variable* mutable_members(int index);
  ::google::cloud::diagnostics::debug::Variable* add_members();
  ::google::protobuf::RepeatedPtrField< ::google::cloud::diagnostics::debug::Variable >*
      mutable_members();
  const ::google::protobuf::RepeatedPtrField< ::google::cloud::diagnostics::debug::Variable >&
      members() const;

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // string value = 3;
  void clear_value();
  static const int kValueFieldNumber = 3;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // .google.cloud.diagnostics.debug.Status status = 5;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 5;
  const ::google::cloud::diagnostics::debug::Status& status() const;
  ::google::cloud::diagnostics::debug::Status* mutable_status();
  ::google::cloud::diagnostics::debug::Status* release_status();
  void set_allocated_status(::google::cloud::diagnostics::debug::Status* status);

  // @@protoc_insertion_point(class_scope:google.cloud.diagnostics.debug.Variable)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::google::cloud::diagnostics::debug::Variable > members_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::cloud::diagnostics::debug::Status* status_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2fbreakpoint_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Status : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.cloud.diagnostics.debug.Status) */ {
 public:
  Status();
  virtual ~Status();

  Status(const Status& from);

  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Status& default_instance();

  static inline const Status* internal_default_instance() {
    return reinterpret_cast<const Status*>(
               &_Status_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Status* other);

  // implements Message ----------------------------------------------

  inline Status* New() const PROTOBUF_FINAL { return New(NULL); }

  Status* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Status& from);
  void MergeFrom(const Status& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Status* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // bool iserror = 1;
  void clear_iserror();
  static const int kIserrorFieldNumber = 1;
  bool iserror() const;
  void set_iserror(bool value);

  // @@protoc_insertion_point(class_scope:google.cloud.diagnostics.debug.Status)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  bool iserror_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2fbreakpoint_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Breakpoint

// string id = 1;
inline void Breakpoint::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Breakpoint::id() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Breakpoint.id)
  return id_.GetNoArena();
}
inline void Breakpoint::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.diagnostics.debug.Breakpoint.id)
}
#if LANG_CXX11
inline void Breakpoint::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.diagnostics.debug.Breakpoint.id)
}
#endif
inline void Breakpoint::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.diagnostics.debug.Breakpoint.id)
}
inline void Breakpoint::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.diagnostics.debug.Breakpoint.id)
}
inline ::std::string* Breakpoint::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Breakpoint.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Breakpoint::release_id() {
  // @@protoc_insertion_point(field_release:google.cloud.diagnostics.debug.Breakpoint.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Breakpoint::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.diagnostics.debug.Breakpoint.id)
}

// .google.cloud.diagnostics.debug.SourceLocation location = 2;
inline bool Breakpoint::has_location() const {
  return this != internal_default_instance() && location_ != NULL;
}
inline void Breakpoint::clear_location() {
  if (GetArenaNoVirtual() == NULL && location_ != NULL) delete location_;
  location_ = NULL;
}
inline const ::google::cloud::diagnostics::debug::SourceLocation& Breakpoint::location() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Breakpoint.location)
  return location_ != NULL ? *location_
                         : *::google::cloud::diagnostics::debug::SourceLocation::internal_default_instance();
}
inline ::google::cloud::diagnostics::debug::SourceLocation* Breakpoint::mutable_location() {
  
  if (location_ == NULL) {
    location_ = new ::google::cloud::diagnostics::debug::SourceLocation;
  }
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Breakpoint.location)
  return location_;
}
inline ::google::cloud::diagnostics::debug::SourceLocation* Breakpoint::release_location() {
  // @@protoc_insertion_point(field_release:google.cloud.diagnostics.debug.Breakpoint.location)
  
  ::google::cloud::diagnostics::debug::SourceLocation* temp = location_;
  location_ = NULL;
  return temp;
}
inline void Breakpoint::set_allocated_location(::google::cloud::diagnostics::debug::SourceLocation* location) {
  delete location_;
  location_ = location;
  if (location) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:google.cloud.diagnostics.debug.Breakpoint.location)
}

// string method_name = 3;
inline void Breakpoint::clear_method_name() {
  method_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Breakpoint::method_name() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Breakpoint.method_name)
  return method_name_.GetNoArena();
}
inline void Breakpoint::set_method_name(const ::std::string& value) {
  
  method_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.diagnostics.debug.Breakpoint.method_name)
}
#if LANG_CXX11
inline void Breakpoint::set_method_name(::std::string&& value) {
  
  method_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.diagnostics.debug.Breakpoint.method_name)
}
#endif
inline void Breakpoint::set_method_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  method_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.diagnostics.debug.Breakpoint.method_name)
}
inline void Breakpoint::set_method_name(const char* value, size_t size) {
  
  method_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.diagnostics.debug.Breakpoint.method_name)
}
inline ::std::string* Breakpoint::mutable_method_name() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Breakpoint.method_name)
  return method_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Breakpoint::release_method_name() {
  // @@protoc_insertion_point(field_release:google.cloud.diagnostics.debug.Breakpoint.method_name)
  
  return method_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Breakpoint::set_allocated_method_name(::std::string* method_name) {
  if (method_name != NULL) {
    
  } else {
    
  }
  method_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), method_name);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.diagnostics.debug.Breakpoint.method_name)
}

// repeated .google.cloud.diagnostics.debug.Variable variables = 4;
inline int Breakpoint::variables_size() const {
  return variables_.size();
}
inline void Breakpoint::clear_variables() {
  variables_.Clear();
}
inline const ::google::cloud::diagnostics::debug::Variable& Breakpoint::variables(int index) const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Breakpoint.variables)
  return variables_.Get(index);
}
inline ::google::cloud::diagnostics::debug::Variable* Breakpoint::mutable_variables(int index) {
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Breakpoint.variables)
  return variables_.Mutable(index);
}
inline ::google::cloud::diagnostics::debug::Variable* Breakpoint::add_variables() {
  // @@protoc_insertion_point(field_add:google.cloud.diagnostics.debug.Breakpoint.variables)
  return variables_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::google::cloud::diagnostics::debug::Variable >*
Breakpoint::mutable_variables() {
  // @@protoc_insertion_point(field_mutable_list:google.cloud.diagnostics.debug.Breakpoint.variables)
  return &variables_;
}
inline const ::google::protobuf::RepeatedPtrField< ::google::cloud::diagnostics::debug::Variable >&
Breakpoint::variables() const {
  // @@protoc_insertion_point(field_list:google.cloud.diagnostics.debug.Breakpoint.variables)
  return variables_;
}

// .google.protobuf.Timestamp create_time = 5;
inline bool Breakpoint::has_create_time() const {
  return this != internal_default_instance() && create_time_ != NULL;
}
inline void Breakpoint::clear_create_time() {
  if (GetArenaNoVirtual() == NULL && create_time_ != NULL) delete create_time_;
  create_time_ = NULL;
}
inline const ::google::protobuf::Timestamp& Breakpoint::create_time() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Breakpoint.create_time)
  return create_time_ != NULL ? *create_time_
                         : *::google::protobuf::Timestamp::internal_default_instance();
}
inline ::google::protobuf::Timestamp* Breakpoint::mutable_create_time() {
  
  if (create_time_ == NULL) {
    create_time_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Breakpoint.create_time)
  return create_time_;
}
inline ::google::protobuf::Timestamp* Breakpoint::release_create_time() {
  // @@protoc_insertion_point(field_release:google.cloud.diagnostics.debug.Breakpoint.create_time)
  
  ::google::protobuf::Timestamp* temp = create_time_;
  create_time_ = NULL;
  return temp;
}
inline void Breakpoint::set_allocated_create_time(::google::protobuf::Timestamp* create_time) {
  delete create_time_;
  if (create_time != NULL && create_time->GetArena() != NULL) {
    ::google::protobuf::Timestamp* new_create_time = new ::google::protobuf::Timestamp;
    new_create_time->CopyFrom(*create_time);
    create_time = new_create_time;
  }
  create_time_ = create_time;
  if (create_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:google.cloud.diagnostics.debug.Breakpoint.create_time)
}

// .google.protobuf.Timestamp final_time = 6;
inline bool Breakpoint::has_final_time() const {
  return this != internal_default_instance() && final_time_ != NULL;
}
inline void Breakpoint::clear_final_time() {
  if (GetArenaNoVirtual() == NULL && final_time_ != NULL) delete final_time_;
  final_time_ = NULL;
}
inline const ::google::protobuf::Timestamp& Breakpoint::final_time() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Breakpoint.final_time)
  return final_time_ != NULL ? *final_time_
                         : *::google::protobuf::Timestamp::internal_default_instance();
}
inline ::google::protobuf::Timestamp* Breakpoint::mutable_final_time() {
  
  if (final_time_ == NULL) {
    final_time_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Breakpoint.final_time)
  return final_time_;
}
inline ::google::protobuf::Timestamp* Breakpoint::release_final_time() {
  // @@protoc_insertion_point(field_release:google.cloud.diagnostics.debug.Breakpoint.final_time)
  
  ::google::protobuf::Timestamp* temp = final_time_;
  final_time_ = NULL;
  return temp;
}
inline void Breakpoint::set_allocated_final_time(::google::protobuf::Timestamp* final_time) {
  delete final_time_;
  if (final_time != NULL && final_time->GetArena() != NULL) {
    ::google::protobuf::Timestamp* new_final_time = new ::google::protobuf::Timestamp;
    new_final_time->CopyFrom(*final_time);
    final_time = new_final_time;
  }
  final_time_ = final_time;
  if (final_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:google.cloud.diagnostics.debug.Breakpoint.final_time)
}

// -------------------------------------------------------------------

// SourceLocation

// string path = 1;
inline void SourceLocation::clear_path() {
  path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SourceLocation::path() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.SourceLocation.path)
  return path_.GetNoArena();
}
inline void SourceLocation::set_path(const ::std::string& value) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.diagnostics.debug.SourceLocation.path)
}
#if LANG_CXX11
inline void SourceLocation::set_path(::std::string&& value) {
  
  path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.diagnostics.debug.SourceLocation.path)
}
#endif
inline void SourceLocation::set_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.diagnostics.debug.SourceLocation.path)
}
inline void SourceLocation::set_path(const char* value, size_t size) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.diagnostics.debug.SourceLocation.path)
}
inline ::std::string* SourceLocation::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.SourceLocation.path)
  return path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SourceLocation::release_path() {
  // @@protoc_insertion_point(field_release:google.cloud.diagnostics.debug.SourceLocation.path)
  
  return path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SourceLocation::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    
  } else {
    
  }
  path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.diagnostics.debug.SourceLocation.path)
}

// int32 line = 2;
inline void SourceLocation::clear_line() {
  line_ = 0;
}
inline ::google::protobuf::int32 SourceLocation::line() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.SourceLocation.line)
  return line_;
}
inline void SourceLocation::set_line(::google::protobuf::int32 value) {
  
  line_ = value;
  // @@protoc_insertion_point(field_set:google.cloud.diagnostics.debug.SourceLocation.line)
}

// -------------------------------------------------------------------

// Variable

// string name = 1;
inline void Variable::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Variable::name() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Variable.name)
  return name_.GetNoArena();
}
inline void Variable::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.diagnostics.debug.Variable.name)
}
#if LANG_CXX11
inline void Variable::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.diagnostics.debug.Variable.name)
}
#endif
inline void Variable::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.diagnostics.debug.Variable.name)
}
inline void Variable::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.diagnostics.debug.Variable.name)
}
inline ::std::string* Variable::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Variable.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Variable::release_name() {
  // @@protoc_insertion_point(field_release:google.cloud.diagnostics.debug.Variable.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Variable::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.diagnostics.debug.Variable.name)
}

// string type = 2;
inline void Variable::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Variable::type() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Variable.type)
  return type_.GetNoArena();
}
inline void Variable::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.diagnostics.debug.Variable.type)
}
#if LANG_CXX11
inline void Variable::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.diagnostics.debug.Variable.type)
}
#endif
inline void Variable::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.diagnostics.debug.Variable.type)
}
inline void Variable::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.diagnostics.debug.Variable.type)
}
inline ::std::string* Variable::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Variable.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Variable::release_type() {
  // @@protoc_insertion_point(field_release:google.cloud.diagnostics.debug.Variable.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Variable::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.diagnostics.debug.Variable.type)
}

// string value = 3;
inline void Variable::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Variable::value() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Variable.value)
  return value_.GetNoArena();
}
inline void Variable::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.diagnostics.debug.Variable.value)
}
#if LANG_CXX11
inline void Variable::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.diagnostics.debug.Variable.value)
}
#endif
inline void Variable::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.diagnostics.debug.Variable.value)
}
inline void Variable::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.diagnostics.debug.Variable.value)
}
inline ::std::string* Variable::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Variable.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Variable::release_value() {
  // @@protoc_insertion_point(field_release:google.cloud.diagnostics.debug.Variable.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Variable::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.diagnostics.debug.Variable.value)
}

// repeated .google.cloud.diagnostics.debug.Variable members = 4;
inline int Variable::members_size() const {
  return members_.size();
}
inline void Variable::clear_members() {
  members_.Clear();
}
inline const ::google::cloud::diagnostics::debug::Variable& Variable::members(int index) const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Variable.members)
  return members_.Get(index);
}
inline ::google::cloud::diagnostics::debug::Variable* Variable::mutable_members(int index) {
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Variable.members)
  return members_.Mutable(index);
}
inline ::google::cloud::diagnostics::debug::Variable* Variable::add_members() {
  // @@protoc_insertion_point(field_add:google.cloud.diagnostics.debug.Variable.members)
  return members_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::google::cloud::diagnostics::debug::Variable >*
Variable::mutable_members() {
  // @@protoc_insertion_point(field_mutable_list:google.cloud.diagnostics.debug.Variable.members)
  return &members_;
}
inline const ::google::protobuf::RepeatedPtrField< ::google::cloud::diagnostics::debug::Variable >&
Variable::members() const {
  // @@protoc_insertion_point(field_list:google.cloud.diagnostics.debug.Variable.members)
  return members_;
}

// .google.cloud.diagnostics.debug.Status status = 5;
inline bool Variable::has_status() const {
  return this != internal_default_instance() && status_ != NULL;
}
inline void Variable::clear_status() {
  if (GetArenaNoVirtual() == NULL && status_ != NULL) delete status_;
  status_ = NULL;
}
inline const ::google::cloud::diagnostics::debug::Status& Variable::status() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Variable.status)
  return status_ != NULL ? *status_
                         : *::google::cloud::diagnostics::debug::Status::internal_default_instance();
}
inline ::google::cloud::diagnostics::debug::Status* Variable::mutable_status() {
  
  if (status_ == NULL) {
    status_ = new ::google::cloud::diagnostics::debug::Status;
  }
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Variable.status)
  return status_;
}
inline ::google::cloud::diagnostics::debug::Status* Variable::release_status() {
  // @@protoc_insertion_point(field_release:google.cloud.diagnostics.debug.Variable.status)
  
  ::google::cloud::diagnostics::debug::Status* temp = status_;
  status_ = NULL;
  return temp;
}
inline void Variable::set_allocated_status(::google::cloud::diagnostics::debug::Status* status) {
  delete status_;
  status_ = status;
  if (status) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:google.cloud.diagnostics.debug.Variable.status)
}

// -------------------------------------------------------------------

// Status

// bool iserror = 1;
inline void Status::clear_iserror() {
  iserror_ = false;
}
inline bool Status::iserror() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Status.iserror)
  return iserror_;
}
inline void Status::set_iserror(bool value) {
  
  iserror_ = value;
  // @@protoc_insertion_point(field_set:google.cloud.diagnostics.debug.Status.iserror)
}

// string message = 2;
inline void Status::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Status::message() const {
  // @@protoc_insertion_point(field_get:google.cloud.diagnostics.debug.Status.message)
  return message_.GetNoArena();
}
inline void Status::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.diagnostics.debug.Status.message)
}
#if LANG_CXX11
inline void Status::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.diagnostics.debug.Status.message)
}
#endif
inline void Status::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.diagnostics.debug.Status.message)
}
inline void Status::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.diagnostics.debug.Status.message)
}
inline ::std::string* Status::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.diagnostics.debug.Status.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Status::release_message() {
  // @@protoc_insertion_point(field_release:google.cloud.diagnostics.debug.Status.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Status::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.diagnostics.debug.Status.message)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace debug
}  // namespace diagnostics
}  // namespace cloud
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fbreakpoint_2eproto__INCLUDED
